---
sudo: required
dist: trusty
language: generic
cache: bundler
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
services: docker
env:
  matrix:
    - INSTANCE=runner-centos-7
    - INSTANCE=runner-centos-6
    - INSTANCE=runner-ubuntu-1604
    - INSTANCE=runner-ubuntu-1404
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-salt
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
  - /opt/chefdk/embedded/bin/chef --version
script: kitchen verify ${INSTANCE}
after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
